{% set name = "google-drive" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eduardogr/google-drive-python/archive/v{{ version }}.tar.gz
  sha256: 45bed1f71ef72bad0e1b7837800b44b394d6278af8551718b0180f059d9405ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - google-drive = googledrive.cli:googledrive

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses ==0.6
    - google-api-python-client ==1.8.0
    - google-auth-httplib2 ==0.0.3
    - google-auth-oauthlib ==0.4.1
    - python >=3.6

test:
  imports:
    - googledrive

about:
  home: https://github.com/eduardogr/google-drive-python
  summary: Library and cli to manage and interact with your Google Drive
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
